# Generated by Django 2.2 on 2020-12-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderquantity',
            name='scan_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderquantity',
            name='scan_status',
            field=models.CharField(blank=True, choices=[('NOT_SCANNED', 'NOT_SCANNED'), ('SCANNED', 'SCANNED'), ('PARTIALLY_SCANNED', 'PARTIALLY_SCANNED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderquantity',
            name='discount',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.ManyToManyField(blank=True, related_name='packs', to='base.ProductPackSizes'),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('image', models.FileField(blank=True, null=True, upload_to='media/')),
                ('amount_recieved', models.PositiveIntegerField(default=0)),
                ('reference_no', models.CharField(max_length=40)),
                ('method', models.CharField(choices=[('CHEQUE', 'CHEQUE'), ('CASH', 'CASH'), ('ONLINE', 'ONLINE TRANSFER')], max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Customer')),
            ],
        ),
    ]
