# Generated by Django 2.2 on 2020-12-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201222_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderquantity',
            name='verfication_scan_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderquantity',
            name='verfication_scan_status',
            field=models.CharField(blank=True, choices=[('NOT_SCANNED', 'NOT_SCANNED'), ('SCANNED', 'SCANNED'), ('PARTIALLY_SCANNED', 'PARTIALLY_SCANNED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PARTIAL', 'PARTIALLY PAID'), ('FULL', 'FULLY PAID'), ('NOT_PAID', 'NOT PAID')], default='NOT_PAID', max_length=10, null=True),
        ),
    ]
