# Generated by Django 2.2 on 2021-01-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201228_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='category',
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.ManyToManyField(null=True, to='base.Categories'),
        ),
    ]
