# Generated by Django 2.2 on 2021-01-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210105_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustproduct',
            name='average_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='adjustproduct',
            name='initial_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='adjustproduct',
            name='initial_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='adjustproduct',
            name='initial_quanity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='adjustproduct',
            name='new_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='adjustproduct',
            name='new_quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adjustproduct',
            name='old_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='adjustproduct',
            name='old_quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='InitialProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('date', models.DateField(null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Product')),
            ],
        ),
    ]
