# Generated by Django 2.2 on 2021-02-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_no',
            field=models.TextField(blank=True, null=True, verbose_name='item_no'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Warehouse Location'),
        ),
    ]
