# Generated by Django 2.2 on 2021-03-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210301_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_no',
            new_name='item_no1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='weight1',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
    ]
