# Generated by Django 2.2 on 2021-03-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210301_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_no1',
            new_name='item_no',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='weight1',
            new_name='weight',
        ),
    ]
