# Generated by Django 2.2 on 2021-03-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20210301_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
