# Generated by Django 2.2 on 2021-03-08 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_order_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_num',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_person',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'SALESPERSON'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sales_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
