# Generated by Django 2.2 on 2021-03-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20210308_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustproduct',
            name='initial_purchase_amount',
            field=models.FloatField(null=True, verbose_name='Initial Purchase Amount'),
        ),
        migrations.AddField(
            model_name='adjustproduct',
            name='new_purchase_price',
            field=models.FloatField(null=True, verbose_name='New Purchase Price'),
        ),
        migrations.AddField(
            model_name='adjustproduct',
            name='old_purchase_price',
            field=models.FloatField(null=True, verbose_name='Old Purchase Price'),
        ),
        migrations.AlterField(
            model_name='adjustproduct',
            name='initial_amount',
            field=models.FloatField(null=True, verbose_name='Initial Sales Amount'),
        ),
        migrations.AlterField(
            model_name='adjustproduct',
            name='new_price',
            field=models.FloatField(null=True, verbose_name='New Sales Price'),
        ),
        migrations.AlterField(
            model_name='adjustproduct',
            name='old_price',
            field=models.FloatField(null=True, verbose_name='Old Sales Price'),
        ),
    ]
