# Generated by Django 2.2 on 2021-03-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_order_ageing'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustproduct',
            name='old_date',
            field=models.DateField(blank=True, null=True, verbose_name='Old Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adjustproduct',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='New Date'),
        ),
    ]
