# Generated by Django 2.2 on 2021-03-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20210325_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sales_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
