# Generated by Django 2.2 on 2021-04-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_order_sales_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderquantity',
            name='product_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
