# Generated by Django 2.2 on 2021-04-06 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_orderquantity_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustproduct',
            name='average_purchase_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='warehouse_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
