# Generated by Django 2.2 on 2021-04-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20210406_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='po_num',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='adjustproduct',
            name='average_price',
            field=models.FloatField(null=True, verbose_name='Average Selling Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ageing',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.ManyToManyField(blank=True, to='base.Categories'),
        ),
    ]
