# Generated by Django 2.2 on 2021-05-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20210513_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mark_up',
        ),
    ]
