# Generated by Django 2.2 on 2021-05-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20210521_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustproduct',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_profit',
            field=models.FloatField(default=0),
        ),
    ]
