# Generated by Django 2.2 on 2021-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20210529_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderquantity',
            name='remaining_scan_quantity',
            field=models.FloatField(default=0),
        ),
    ]
