# Generated by Django 2.2 on 2021-06-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_orderquantity_remaining_scan_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderquantity',
            name='remaining_verfication_scan_quantity',
            field=models.FloatField(default=0),
        ),
    ]
