# Generated by Django 2.2 on 2021-06-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_orderquantity_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
