# Generated by Django 2.2 on 2021-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_order_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderquantity',
            name='product_purchase_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='orderquantity',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Product Sales Price'),
        ),
    ]
