# Generated by Django 2.2 on 2021-09-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20210621_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_credit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_profit_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderquantity',
            name='net_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Order'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='method',
            field=models.CharField(choices=[('CHECK', ' CHECK'), ('CASH', 'CASH'), ('ONLINE', 'ONLINE TRANSFER')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CreditMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_no', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_amount', models.FloatField(blank=True, default=0, null=True)),
                ('open_balance', models.FloatField(blank=True, default=0, null=True)),
                ('credit_amount', models.FloatField(blank=True, default=0, null=True)),
                ('updated_credit_amount', models.FloatField(blank=True, default=0, null=True)),
                ('credit_applied_status', models.CharField(blank=True, choices=[('FULLY', 'FULLY'), ('PARTIALLY', 'PARTIALLY')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('credit_memo_pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Order')),
                ('payment_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PaymentHistory')),
            ],
        ),
        migrations.CreateModel(
            name='CreditApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_amount', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('credit_applied_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Order')),
                ('credit_memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CreditMemo')),
            ],
        ),
    ]
